apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
  namespace: k8s-workshop
spec:
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: quay.io/reactiveops/k8s-workshop:latest
          command: ["ruby", "app/app.rb"]
          livenessProbe:
            httpGet:
              path: /app
              port:
            initialDelaySeconds:
            periodSeconds:
            timeoutSeconds:
            failureThreshold:
            successThreshold:
          readinessProbe:
            httpGet:
              path: /app
              port:
            initialDelaySeconds:
            periodSeconds:
            timeoutSeconds:
            failureThreshold:
            successThreshold:
          ports:
          - containerPort: 8080
            name: http
          volumeMounts:
            - name: secrets
              mountPath: "/etc/secrets"
          env:
            - name: REDIS_HOST
              value: 'redis-primary'
            - name: REDIS_PORT
              value: '6379'
            - name: SECRET1
              valueFrom:
                secretKeyRef:
                  name: webapp
                  key: val1
            - name: DEPENDENCY_URL
              valueFrom:
                configMapKeyRef:
                  name: webapp
                  key: app.dependency.url
            - name: DEPENDENCY_REQUIRE_TLS
              valueFrom:
                configMapKeyRef:
                  name: webapp
                  key: app.dependency.require_tls
      volumes:
        - name: secrets
          secret:
            secretName: webapp
            items:
            - key: val2
              path: secret_file
              mode: 511
