apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
  namespace: k8s-workshop
spec:
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: us.gcr.io/ehole-k8s/webapp:2
          command: ["ruby", "app/app.rb"]
          ports:
          - containerPort: 8080
            name: http
          volumeMounts:
            - name: secrets
              mountPath: "/etc/secrets"
          env:
            - name: REDIS_HOST
              value: 'redis-primary'
            - name: REDIS_PORT
              value: '6379'
            - name: SECRET1
              valueFrom:
                secretKeyRef:
                  name: webapp
                  key:
            - name: DEPENDENCY_URL
              valueFrom:
                configMapKeyRef:
                  name: webapp
                  key:
            - name: DEPENDENCY_REQUIRE_TLS
              valueFrom:
                configMapKeyRef:
                  name: webapp
                  key:
      volumes:
        - name: secrets
          secret:
            secretName: webapp
            items:
            - key:
              path: secret_file
              mode: 511
